version: '2'
services:
  mongo:
    image: mongo
    networks:
      - dk
    volumes:
      - mongodata:/data/db
  crowdwisdom:
    ports:
      - "4005:4005"
    # image: levinb/crowdwisdom:0.0.1
    networks:
      - dk
    environment:
      - N_WORKERS=2
      - PORT=4005
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_DB=slack
      - CLIENT_ID
      - CLIENT_SECRET
      - VERIFICATION_TOKEN
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile.backend
networks:
  dk:
    driver: bridge
volumes:
  mongodata:
    driver: local
